function imfp_formalism_list = read_imfp_formalisms()
% imfp_formalism_list = read_imfp_formalisms()
%   This function returns a cell array containing all the formalisms used for
%   the IMFP calculations.
%
%   IN: (none)
%
%   OUT:
%   -   imfp_formalism_list:      1x10 cell array of all IMFP formalisms

%% 1 : Defining all IMFP formalisms
imfp_formalism_list   = {...
    "JTP(2023)"...
    "S4(2012)",...
    "S3O(2012)",...
    "S3(2012)",...
    "S2(2011)",...
    "S1(2011)",...
    "NIST(1999)",...
    "TPP2M-avg(1994)",...
    "TPP2M(1994)",...
    "Universal(1979)",...
    };
end